{% set name = "gilknocker" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gilknocker-{{ version }}.tar.gz
  sha256: 6fa39689e3ddfc9c5a4bbb8684a7a3d0706e40c207d26679edc634c0c4a721d5

build:
  number: 0
  script:
    {% if build_platform != target_platform %}
    - export PYO3_CROSS_INCLUDE_DIR=$PREFIX/include
    - export PYO3_CROSS_LIB_DIR=$PREFIX/lib/python$PY_VER
    - export PYO3_CROSS_PYTHON_VERSION=$PY_VER
    {% endif %}
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - toml                                   # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}                    # [unix]
    - {{ compiler('m2w64_c') }}              # [win]
  host:
    - python
    - pip
    - maturin >=0.14,<0.15
    - toml
  run:
    - python

test:
  imports:
    - gilknocker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/milesgranger/gilknocker
  summary: Knock on the Python GIL, determine how busy it is.
  license: MIT AND Unlicense
  license_file:
    - LICENSE-MIT
    - LICENSE

extra:
  recipe-maintainers:
    - milesgranger
